### ISSUE TITLE
ImageBindModel.forward() got an unexpected keyword argument 'post_process'

### ISSUE THREAD

**Issue by wendellgithub0206** [sail-sg/BindDiffusion#11]
![image](https://github.com/sail-sg/BindDiffusion/assets/61726383/da023399-e539-487d-94e2-05e57d480784)
Audio-conditioned image generation Error
![image](https://github.com/sail-sg/BindDiffusion/assets/61726383/ecfe534e-4ca8-4b5e-9996-006c92843be8)

I'm almost done, the last error I can't find a solution to online, hope someone can help me :(

**Comment by xuxy09** [comment]
hi, you can just remove the "post_process" argument.

**Comment by wendellgithub0206** [comment]
> 嗨，您可以刪除“post_process”參數。


Thank you for your reply. I have already translated the image at the end but the RAM of the GPU is not enough. I would like to ask how many computing resources are needed to run such a code?

![image](https://github.com/sail-sg/BindDiffusion/assets/61726383/4d44ced2-d147-4e24-8597-444ad7dc72b5)

I am using the GPU V100 16GB provided by Google Colab pro
CPU 25GB but GPU RAM is still not enough
