### ISSUE TITLE
Error when running main_bind.py

### ISSUE THREAD

**Issue by v-1024** [sail-sg/BindDiffusion#6]
Hi, thanks for the great work on this!

I had an error running `main_bind.py` in the code `pl_sd = torch.load(ckpt, map_location="cpu")`, which is: `_pickl. UnpicklingError: invalid load key, '<'.`

I checked the `sd21-unclip-h.ckpt` file and found the html content in the file. I think the error should be related to this. I tried to solve this problem, but failed. If possible, could you please answer it for me? 

Thanks!

**Comment by ikuinen** [comment]
Hi, thanks for your interest. I guess you should re-download the checkpoint. This error may caused by your fragmentary model.  The md5sum of `sd21-unclip-h.ckpt` is `72fa8487b729d638a9f4e16b9fb2091a` and maybe you can check it.

**Comment by v-1024** [comment]
Hi，according to your suggestion, the problem has been solved. Thank you for your answer！
